name: Criação de MuleSoft Application
description: Criação de repositório de MuleSoft Application
title: "Criação de Repositório"
labels: ["MuleSoft"]
assignees:
  - ${{github.author}}
body:
  - type: markdown
    attributes:
      value: |
        Formulário padrão para criação de repositório no GitHub Itaú Corp
  - type: input
    id: name
    attributes:
      label: ">>Nome_da_aplicacao<<"
      description: Nome da aplicacao
      placeholder: itau-fx6-app-test-01
    validations:
      required: true
  - type: input
    id: acronym
    attributes:
      label: ">>Sigla_do_produto<<"
      description: Sigla do produto
      placeholder: IU2
    validations:
      required: true
  - type: dropdown
    id: applicationType
    attributes:
      label: ">>Tipo_do_aplicacao<<"
      description: Tipo do apliacao
      options:
        - Experience API
        - Process API
        - System API
        - Domain API
        - Batch Application
    validations:
      required: true
  - type: checkboxes
    id: visualizerLabels
    attributes:
      label: ">>Rotulos_para_Anypoint_Visualizer<<"
      description: Rótulos para Anypoint Visualizer
      options:
        - label: E_uma_Async_API?
          id: isAsyncAPI
