name: Criação de MuleSoft Application
description: Criação de repositório de MuleSoft Application
title: "Criação de Repositório"
labels: ["application", "MuleSoft", "repositorio", "documentation"]
assignees:
  - ${{github.author}}
body:
  - type: markdown
    attributes:
      value: |
        Formulário padrão para criação de repositório no GitHub Itaú Corp
  - type: input
    id: name
    attributes:
      label: ">>Nome da aplicação<<"
      description: Nome da aplicação
      placeholder: itau-fx6-app-test-01
    validations:
      required: true
  - type: input
    id: acronym
    attributes:
      label: ">>Sigla do producto<<"
      description: Sigla do producto
      placeholder: IU2
    validations:
      required: true
  - type: dropdown
    id: application type
    attributes:
      label: ">>Tipo de aplicação<<"
      description: Tipo de aplicação
      options:
        - Experience API
        - Process API
        - System API
        - Batch Application
  - type: checkboxes
    id: visualizer labels
    attributes:
      label: ">>Rótulos para Anypoint Visualizer<<"
      description: Rótulos para Anypoint Visualizer
      options:
        - name: Option 1
          value: opt1
        - name: Option 2
          value: opt2
        - name: Option 3
          value: opt3
      validations:
        allowMultiple: true
